[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.0"

[features]
resolution = false
skip-lint = false
seeds = true

[programs.localnet]
sentinel = "C2WJzwp5XysqRm5PQuM6ZTAeYxxhRyUWf3UJnZjVqMV5"

[programs.devnet]
sentinel = "C2WJzwp5XysqRm5PQuM6ZTAeYxxhRyUWf3UJnZjVqMV5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./ma-cle-pro.json"

[scripts]
test = "npx mocha -r ts-node/register tests/**/*.ts --timeout 1000000"

[test]
startup_wait = 20000

[workspace]
members = ["programs/*"]